# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - uses: pnpm/action-setup@v4
            name: Install pnpm
            with:
              version: 8
              run_install: false

          - name: Install Node.js
            uses: actions/setup-node@v4
            with:
              node-version: 20
              cache: "pnpm"

          - name: Get pnpm store directory
            shell: bash
            run: |
              echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

          - name: Install dependencies
            run: pnpm install

          - run: pnpm ci
          - run: pnpm run build
          - run: pnpm run export

          - name: Deploy 🚀
            uses: JamesIves/github-pages-deploy-action@v4.2.5
            with:
              branch: gh-pages
              folder: out
